import React, { useState } from 'react';
import type { SearchSource } from '../types';

interface ArticleDisplayProps {
  title: string;
  content: string;
  sources?: SearchSource[];
}

export const ArticleDisplay: React.FC<ArticleDisplayProps> = ({
  title,
  content,
  sources = []
}) => {
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState<'txt' | 'md' | 'html'>('txt');
  const [showSources, setShowSources] = useState(false);

  const handleCopy = async () => {
    const textToCopy = title ? `${title}\n\n${content}` : content;
    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const exportAsTxt = () => {
    let textToExport = `Title: ${title || 'Untitled Article'}\n${'='.repeat(50)}\n\n${cleanContent}`;
    if (sources.length > 0) {
      textToExport += '\n\n' + '='.repeat(50) + '\nSources:\n';
      sources.forEach((s, i) => {
        textToExport += `\n${i + 1}. ${s.title}\n   URL: ${s.url}\n`;
      });
    }
    downloadFile(textToExport, 'article.txt', 'text/plain');
  };

  const exportAsMd = () => {
    let mdContent = `# ${title || 'Untitled Article'}\n\n${cleanContent}\n\n---\n`;
    if (sources.length > 0) {
      mdContent += '\n## Sources\n\n';
      sources.forEach((s, i) => {
        mdContent += `${i + 1}. [${s.title}](${s.url})\n`;
      });
    }
    mdContent += '\n---\n*Generated by Article Generator*';
    downloadFile(mdContent, 'article.md', 'text/markdown');
  };

  const exportAsHtml = () => {
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title || 'Untitled Article'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }
    h1 { color: #1a1a1a; margin-bottom: 1rem; }
    .meta { color: #666; font-size: 0.9rem; margin-bottom: 2rem; }
    .content { white-space: pre-wrap; }
    .sources { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee; }
    .sources h2 { font-size: 1.2rem; margin-bottom: 1rem; }
    .source { margin-bottom: 0.5rem; }
    .source a { color: #0066cc; }
  </style>
</head>
<body>
  <h1>${title || 'Untitled Article'}</h1>
  <div class="content">${cleanContent.replace(/\n/g, '<br>')}</div>
  ${sources.length > 0 ? `
  <div class="sources">
    <h2>Sources</h2>
    ${sources.map((s, i) => `<div class="source">${i + 1}. <a href="${s.url}">${s.title}</a></div>`).join('')}
  </div>
  ` : ''}
  <hr>
  <p class="meta">Generated by Article Generator</p>
</body>
</html>`;
    downloadFile(htmlContent, 'article.html', 'text/html');
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleExport = () => {
    switch (exportFormat) {
      case 'txt':
        exportAsTxt();
        break;
      case 'md':
        exportAsMd();
        break;
      case 'html':
        exportAsHtml();
        break;
    }
  };

  // Clean content by removing [Title] and [Content] markers
  const cleanContent = content.replace(/\[Title\]\s*.*?\n*\[Content\]\s*/gi, '');
  
  // Count both English words and Chinese characters
  const countContent = (text: string) => {
    // Count English words (sequences of a-zA-Z)
    const englishWords = text.match(/[a-zA-Z]+/g) || [];
    const englishCount = englishWords.reduce((sum, word) => sum + word.length, 0);
    
    // Count Chinese characters (CJK Unicode range)
    const chineseChars = text.match(/[\u4e00-\u9fff]/g) || [];
    const chineseCount = chineseChars.length;
    
    // Count other characters (numbers, punctuation, etc.)
    const otherChars = text.replace(/[a-zA-Z]+/g, '').replace(/[\u4e00-\u9fff]/g, '').length;
    
    return {
      total: text.length,
      englishWords: englishWords.length,
      englishChars: englishCount,
      chineseChars: chineseCount,
      otherChars: otherChars
    };
  };
  
  const stats = countContent(cleanContent);

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-4">
      <div className="flex justify-between items-start mb-4">
        <h3 className="text-lg font-medium text-gray-900">Generated Article</h3>
        
        {content && (
          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="flex items-center px-3 py-1.5 text-sm bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
            >
              {copied ? (
                <>
                  <svg className="w-4 h-4 mr-1 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy
                </>
              )}
            </button>
            
            <select
              value={exportFormat}
              onChange={(e) => setExportFormat(e.target.value as any)}
              className="px-2 py-1.5 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="txt">.txt</option>
              <option value="md">.md</option>
              <option value="html">.html</option>
            </select>
            
            <button
              onClick={handleExport}
              className="flex items-center px-3 py-1.5 text-sm bg-blue-600 text-white hover:bg-blue-700 rounded-lg transition-colors"
            >
              <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Export
            </button>
          </div>
        )}
      </div>
      
      {content ? (
        <div className="space-y-4">
          {title && (
            <div className="border-b border-gray-200 pb-3">
              <h1 className="text-2xl font-bold text-gray-900">{title}</h1>
            </div>
          )}
          
          <div className="prose max-w-none">
            <div className="whitespace-pre-wrap text-gray-700 leading-relaxed">
              {cleanContent}
            </div>
          </div>
          
          <div className="flex items-center justify-between pt-3 border-t border-gray-200">
            <div className="flex items-center space-x-4 text-sm text-gray-500">
              <span>中文字数: {stats.chineseChars}</span>
              <span>英文单词: {stats.englishWords}</span>
              <span>总字符: {stats.total}</span>
            </div>
            
            {sources.length > 0 && (
              <button
                onClick={() => setShowSources(!showSources)}
                className="text-sm text-blue-600 hover:text-blue-800"
              >
                {showSources ? 'Hide Sources' : `Show ${sources.length} Sources`}
              </button>
            )}
          </div>

          {showSources && sources.length > 0 && (
            <div className="mt-4 p-4 bg-gray-50 rounded-lg">
              <h4 className="text-sm font-medium text-gray-700 mb-3">Sources</h4>
              <div className="space-y-2">
                {sources.map((source, index) => (
                  <div key={index} className="text-sm">
                    <a
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 hover:text-blue-800 underline"
                    >
                      {source.title}
                    </a>
                    <p className="text-gray-500 text-xs mt-1">{source.site}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="text-center py-12 text-gray-500">
          <svg className="w-12 h-12 mx-auto mb-3 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <p>No article generated yet</p>
          <p className="text-sm mt-1">Add snippets and generate an article to see it here</p>
        </div>
      )}
    </div>
  );
};

export default ArticleDisplay;
